### ISSUE TITLE
User interactions must be disabled

### ISSUE THREAD

**Issue by MrPingPong** [googleads/googleads-mobile-ios-native-templates#2]
Getting following warning while using these templates on ios >= 13 (did not try on old version)
`<Google> User interactions must be disabled on the asset view to enable click handling.
userInteractionEnabled has been set to NO on <UIButton: 0x7fbd1548f2a0; frame = (110.667 60; 282.333 31); opaque = NO; autoresize = RM+BM; userInteractionEnabled = NO; layer = <CALayer: 0x600001deffe0>>.`

I am putting this inside UITableViewCell and tried to disable the user interaction for all the child views.. but it did not help.

**Comment by MrPingPong** [comment]
I was able to modify the xib and disable the user interaction.

**Comment by VisheshStegowl** [comment]
@MrPingPong  how can i modify the xib?
