### ISSUE TITLE
Swift Version?

### ISSUE THREAD

**Issue by mmdock** [googleads/googleads-mobile-ios-native-templates#3]
It would be nice to have a swift version for this

**Comment by BaoDotMark** [comment]
SDK 8.0 has replaced **GADUnifiedNativeAdView**  with  **GADNativeAdView**, please update these templates too

**Comment by diamont1001** [comment]
swiftUI version please

**Comment by exepr0gaming** [comment]
Why should native advertising be done with stones and sticks? Will there be updates for SwitfUI? ((

**Comment by stjfk** [comment]
swift version?

**Comment by ericleich** [comment]
Although the code for this project is open source with editable layouts, the primary use case of this project is to let you avoid having to write the layout yourself and style them through https://developers.google.com/admob/ios/native/templates#style_dictionary_keys. If you are looking to modify layouts yourself, [see here](https://github.com/googleads/googleads-mobile-ios-examples/blob/main/Swift/advanced/SwiftUIDemo/SwiftUIDemo/Native/NativeContentView.swift) for a SwiftUI project showing how to lay out a native ad.

**Comment by JillSong** [comment]
Recorded the feature request. Closing the issue.
